### ISSUE TITLE
Singular, plural, or both

### ISSUE THREAD

**Issue by tarleb** [pandoc/scholarly-metadata#6]
Pandoc, by default, uses singular fields like `author` and `institute`, while manubot uses plural names like `authors` and `affiliations`, and JOSS uses a mix (`authors`, `affiliations` at the top level, `affiliation` as an author property).

My suggestion would be to declare both versions valid, with the singular field taking precedence if both are given. So all of the following would be equivalent:

``` yaml
author:
  - name: John Doe
    affiliation: 1
```

``` yaml
authors:
  - name: John Doe
    affiliations: 1
```

``` yaml
authors:
  - name: John Doe
    affiliation: 1
    affiliations: this is ignored
```
